// Generates the renderer's bridge from the Wails binding declarations.
//
// The bridge has to export the same 53 names with the same signatures the
// interface already imports, so the Vue application moves across untouched.
// Transcribing them by hand is the step most likely to introduce a silent
// mismatch — a swapped argument or a dropped method — so it is generated from
// the declarations instead, and a test compares the two surfaces.
//
// Usage: node tools/generate-bridge.mjs <Service.d.ts> <models.ts> <out-dir>

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const [declarations, models, outDir] = process.argv.slice(2);
if (!declarations || !models || !outDir) {
  console.error("usage: generate-bridge.mjs <Service.d.ts> <models.ts> <out-dir>");
  process.exit(1);
}

const source = readFileSync(declarations, "utf8");
const pattern = /^export function (\w+)\(([^)]*)\):Promise<(.+)>;$/gm;

const methods = [];
for (const match of source.matchAll(pattern)) {
  const [, name, rawArgs, result] = match;
  const args = rawArgs
    .split(",")
    .map((arg) => arg.trim())
    .filter(Boolean)
    .map((arg) => {
      const [argName, type] = arg.split(":");
      return { name: argName, type };
    });
  methods.push({ name, args, result });
}

if (methods.length === 0) {
  console.error(`no bindings found in ${declarations}`);
  process.exit(1);
}

const lines = [
  "// This file is generated by tools/generate-bridge.mjs. DO NOT EDIT.",
  "//",
  "// It mirrors the Wails binding surface so the interface can move to the",
  "// Electron shell without changing a single call site.",
  "",
  `import { appservice, plugin } from "./${basename(models, ".ts")}";`,
  "",
  "/** The shell's bridge, installed by the preload script. */",
  "declare global {",
  "  interface Window {",
  "    aiclaw: {",
  "      invoke(command: string, ...params: unknown[]): Promise<unknown>;",
  "      commands(): Promise<string[]>;",
  "      on(name: string, handler: (...args: unknown[]) => void): () => void;",
  "      pathForFile(file: File): string;",
  "      openExternal(url: string): Promise<void>;",
  "      openPath(path: string): Promise<string>;",
  "      showItemInFolder(path: string): Promise<void>;",
  "    };",
  "  }",
  "}",
  "",
  "function invoke<T>(command: string, params: unknown[]): Promise<T> {",
  "  return window.aiclaw.invoke(command, ...params) as Promise<T>;",
  "}",
  "",
];

for (const method of methods) {
  const params = method.args.map((arg) => `${arg.name}: ${arg.type}`).join(", ");
  const forwarded = method.args.map((arg) => arg.name).join(", ");
  const returns = method.result === "void" ? "void" : method.result;
  lines.push(
    `export function ${method.name}(${params}): Promise<${returns}> {`,
    `  return invoke<${returns}>("${method.name}", [${forwarded}]);`,
    "}",
    "",
  );
}

lines.push(
  "/** Every command this bridge can reach, for the startup contract check. */",
  "export const bridgeCommands: readonly string[] = [",
  ...methods.map((method) => `  "${method.name}",`),
  "];",
  "",
);

mkdirSync(outDir, { recursive: true });
const target = join(outDir, "bridge.ts");
writeFileSync(target, lines.join("\n"));
console.log(`generated ${methods.length} bridge functions into ${target}`);
