// This file is generated by tools/generate-bridge.mjs. DO NOT EDIT.
//
// It mirrors the Wails binding surface so the interface can move to the
// Electron shell without changing a single call site.

import { appservice, plugin } from "./models";

/** The shell's bridge, installed by the preload script. */
declare global {
  interface Window {
    aiclaw: {
      invoke(command: string, ...params: unknown[]): Promise<unknown>;
      commands(): Promise<string[]>;
      on(name: string, handler: (...args: unknown[]) => void): () => void;
      pathForFile(file: File): string;
      openExternal(url: string): Promise<void>;
      openPath(path: string): Promise<string>;
      showItemInFolder(path: string): Promise<void>;
    };
  }
}

function invoke<T>(command: string, params: unknown[]): Promise<T> {
  return window.aiclaw.invoke(command, ...params) as Promise<T>;
}

export function AddMCPServer(arg1: appservice.MCPServerInput): Promise<appservice.DesktopMCPServer> {
  return invoke<appservice.DesktopMCPServer>("AddMCPServer", [arg1]);
}

export function AddProvider(arg1: appservice.ProviderInput): Promise<appservice.DesktopProvider> {
  return invoke<appservice.DesktopProvider>("AddProvider", [arg1]);
}

export function AddProviderModel(arg1: number, arg2: string): Promise<appservice.DesktopProvider> {
  return invoke<appservice.DesktopProvider>("AddProviderModel", [arg1, arg2]);
}

export function AddSearchEngine(arg1: appservice.SearchEngineInput): Promise<appservice.DesktopSearchEngine> {
  return invoke<appservice.DesktopSearchEngine>("AddSearchEngine", [arg1]);
}

export function ApproveMemory(arg1: string): Promise<void> {
  return invoke<void>("ApproveMemory", [arg1]);
}

export function ArchiveThread(arg1: string): Promise<void> {
  return invoke<void>("ArchiveThread", [arg1]);
}

export function AuthorizeChannelBinding(arg1: string, arg2: string, arg3: string, arg4: number, arg5: string, arg6: Array<string>): Promise<void> {
  return invoke<void>("AuthorizeChannelBinding", [arg1, arg2, arg3, arg4, arg5, arg6]);
}

export function BackgroundChats(): Promise<Array<appservice.BackgroundChat>> {
  return invoke<Array<appservice.BackgroundChat>>("BackgroundChats", []);
}

export function ChannelBindings(): Promise<Array<appservice.DesktopChannelBinding>> {
  return invoke<Array<appservice.DesktopChannelBinding>>("ChannelBindings", []);
}

export function ChannelStatus(): Promise<Array<plugin.ChannelStatus>> {
  return invoke<Array<plugin.ChannelStatus>>("ChannelStatus", []);
}

export function Chat(arg1: appservice.ChatProfile, arg2: string, arg3: string, arg4: Array<string>): Promise<appservice.ChatResult> {
  return invoke<appservice.ChatResult>("Chat", [arg1, arg2, arg3, arg4]);
}

export function ChooseAttachments(): Promise<Array<appservice.DesktopAttachment>> {
  return invoke<Array<appservice.DesktopAttachment>>("ChooseAttachments", []);
}

export function ChoosePluginDirectory(): Promise<appservice.DesktopPlugin> {
  return invoke<appservice.DesktopPlugin>("ChoosePluginDirectory", []);
}

export function CreateProject(arg1: string): Promise<appservice.DesktopProject> {
  return invoke<appservice.DesktopProject>("CreateProject", [arg1]);
}

export function DeleteMCPServer(arg1: string): Promise<void> {
  return invoke<void>("DeleteMCPServer", [arg1]);
}

export function DeletePlugin(arg1: string): Promise<void> {
  return invoke<void>("DeletePlugin", [arg1]);
}

export function DeleteProject(arg1: string): Promise<void> {
  return invoke<void>("DeleteProject", [arg1]);
}

export function DeleteProvider(arg1: number): Promise<void> {
  return invoke<void>("DeleteProvider", [arg1]);
}

export function DeleteSearchEngine(arg1: number): Promise<void> {
  return invoke<void>("DeleteSearchEngine", [arg1]);
}

export function DiscardAttachment(arg1: string): Promise<void> {
  return invoke<void>("DiscardAttachment", [arg1]);
}

export function ForgetMemory(arg1: string): Promise<void> {
  return invoke<void>("ForgetMemory", [arg1]);
}

export function ImportAttachments(arg1: Array<string>): Promise<Array<appservice.DesktopAttachment>> {
  return invoke<Array<appservice.DesktopAttachment>>("ImportAttachments", [arg1]);
}

export function LastModelSelection(): Promise<appservice.DesktopModelSelection> {
  return invoke<appservice.DesktopModelSelection>("LastModelSelection", []);
}

export function MCPServers(): Promise<Array<appservice.DesktopMCPServer>> {
  return invoke<Array<appservice.DesktopMCPServer>>("MCPServers", []);
}

export function Memories(): Promise<Array<appservice.DesktopMemory>> {
  return invoke<Array<appservice.DesktopMemory>>("Memories", []);
}

export function MemorySettings(): Promise<appservice.DesktopMemorySettings> {
  return invoke<appservice.DesktopMemorySettings>("MemorySettings", []);
}

export function MoveThreadToProject(arg1: string, arg2: string): Promise<void> {
  return invoke<void>("MoveThreadToProject", [arg1, arg2]);
}

export function OpenAttachment(arg1: string): Promise<void> {
  return invoke<void>("OpenAttachment", [arg1]);
}

export function OpenOutputFile(arg1: string): Promise<void> {
  return invoke<void>("OpenOutputFile", [arg1]);
}

export function PluginConfigFields(arg1: string): Promise<Array<plugin.Field>> {
  return invoke<Array<plugin.Field>>("PluginConfigFields", [arg1]);
}

export function Plugins(): Promise<Array<appservice.DesktopPlugin>> {
  return invoke<Array<appservice.DesktopPlugin>>("Plugins", []);
}

export function PollWeChatLogin(arg1: string, arg2: string): Promise<appservice.WeChatLoginStatus> {
  return invoke<appservice.WeChatLoginStatus>("PollWeChatLogin", [arg1, arg2]);
}

export function Projects(): Promise<Array<appservice.DesktopProject>> {
  return invoke<Array<appservice.DesktopProject>>("Projects", []);
}

export function Providers(): Promise<Array<appservice.DesktopProvider>> {
  return invoke<Array<appservice.DesktopProvider>>("Providers", []);
}

export function RemoveProviderModel(arg1: number, arg2: string): Promise<appservice.DesktopProvider> {
  return invoke<appservice.DesktopProvider>("RemoveProviderModel", [arg1, arg2]);
}

export function Retry(arg1: appservice.ChatProfile, arg2: string): Promise<appservice.ChatResult> {
  return invoke<appservice.ChatResult>("Retry", [arg1, arg2]);
}

export function RevealAttachment(arg1: string): Promise<void> {
  return invoke<void>("RevealAttachment", [arg1]);
}

export function RevealOutputFile(arg1: string): Promise<void> {
  return invoke<void>("RevealOutputFile", [arg1]);
}

export function RevokeChannelBinding(arg1: string, arg2: string, arg3: string): Promise<void> {
  return invoke<void>("RevokeChannelBinding", [arg1, arg2, arg3]);
}

export function SearchEngines(): Promise<Array<appservice.DesktopSearchEngine>> {
  return invoke<Array<appservice.DesktopSearchEngine>>("SearchEngines", []);
}

export function SetLastModelSelection(arg1: number, arg2: string): Promise<void> {
  return invoke<void>("SetLastModelSelection", [arg1, arg2]);
}

export function SetMemorySettings(arg1: boolean, arg2: boolean): Promise<void> {
  return invoke<void>("SetMemorySettings", [arg1, arg2]);
}

export function SetPluginConfig(arg1: string, arg2: string, arg3: string): Promise<void> {
  return invoke<void>("SetPluginConfig", [arg1, arg2, arg3]);
}

export function StartChat(arg1: appservice.ChatProfile, arg2: string, arg3: string, arg4: Array<string>): Promise<appservice.ChatStartResult> {
  return invoke<appservice.ChatStartResult>("StartChat", [arg1, arg2, arg3, arg4]);
}

export function StartRetry(arg1: appservice.ChatProfile, arg2: string): Promise<appservice.ChatStartResult> {
  return invoke<appservice.ChatStartResult>("StartRetry", [arg1, arg2]);
}

export function StartWeChatLogin(): Promise<appservice.WeChatLoginQR> {
  return invoke<appservice.WeChatLoginQR>("StartWeChatLogin", []);
}

export function Status(): Promise<string> {
  return invoke<string>("Status", []);
}

export function SyncProviderModels(arg1: number): Promise<Array<string>> {
  return invoke<Array<string>>("SyncProviderModels", [arg1]);
}

export function ThreadMessages(arg1: string): Promise<Array<appservice.DesktopMessage>> {
  return invoke<Array<appservice.DesktopMessage>>("ThreadMessages", [arg1]);
}

export function Threads(): Promise<Array<appservice.DesktopThread>> {
  return invoke<Array<appservice.DesktopThread>>("Threads", []);
}

export function ToggleMCPServer(arg1: string, arg2: boolean): Promise<void> {
  return invoke<void>("ToggleMCPServer", [arg1, arg2]);
}

export function TogglePlugin(arg1: string, arg2: boolean): Promise<void> {
  return invoke<void>("TogglePlugin", [arg1, arg2]);
}

export function ToggleSearchEngine(arg1: number, arg2: boolean): Promise<void> {
  return invoke<void>("ToggleSearchEngine", [arg1, arg2]);
}

/** Every command this bridge can reach, for the startup contract check. */
export const bridgeCommands: readonly string[] = [
  "AddMCPServer",
  "AddProvider",
  "AddProviderModel",
  "AddSearchEngine",
  "ApproveMemory",
  "ArchiveThread",
  "AuthorizeChannelBinding",
  "BackgroundChats",
  "ChannelBindings",
  "ChannelStatus",
  "Chat",
  "ChooseAttachments",
  "ChoosePluginDirectory",
  "CreateProject",
  "DeleteMCPServer",
  "DeletePlugin",
  "DeleteProject",
  "DeleteProvider",
  "DeleteSearchEngine",
  "DiscardAttachment",
  "ForgetMemory",
  "ImportAttachments",
  "LastModelSelection",
  "MCPServers",
  "Memories",
  "MemorySettings",
  "MoveThreadToProject",
  "OpenAttachment",
  "OpenOutputFile",
  "PluginConfigFields",
  "Plugins",
  "PollWeChatLogin",
  "Projects",
  "Providers",
  "RemoveProviderModel",
  "Retry",
  "RevealAttachment",
  "RevealOutputFile",
  "RevokeChannelBinding",
  "SearchEngines",
  "SetLastModelSelection",
  "SetMemorySettings",
  "SetPluginConfig",
  "StartChat",
  "StartRetry",
  "StartWeChatLogin",
  "Status",
  "SyncProviderModels",
  "ThreadMessages",
  "Threads",
  "ToggleMCPServer",
  "TogglePlugin",
  "ToggleSearchEngine",
];
