/** Exercises the real Vue/preload workflow without touching user data or paid models. */
const {app,BrowserWindow,ipcMain}=require('electron');
const {join}=require('node:path');
const {writeFileSync,readFileSync}=require('node:fs');
const desktop=join(__dirname,'../apps/desktop');
const {IPC}=require(join(desktop,'dist/shared/ipc.cjs'));
app.setPath('userData',join(app.getPath('temp'),'aiclaw-work-smoke'));
let win;
const checks=[];
function check(name,ok){checks.push({name,ok});console.log(`${ok?'ok':'FAIL'} ${name}`);}
app.whenReady().then(async()=>{
 const config={providerId:1,model:'test',reasoningEffort:'medium',contextWindow:0,workdir:'/tmp/smoke',profile:'on-write',language:'zh-CN'};
 let goal=null,forked=false;const sends=[],forks=[],recoveries=[];let sessionTitle='Workflow test',sessionWorkspace='/tmp/smoke',renameFails=false;const renameCalls=[];
 let mcpServers=[{id:'remote',label:'remote',url:'https://fixture.example/mcp',transport:'http',enabled:false,oauth:true}],authState='needs_login';const authCalls=[],scheduleInputs=[];let tasks=[];
 let pending=[{requestId:'q',state:'queued',payload:{text:'queued input'},turnId:'t1',createdAt:1},{requestId:'u',state:'uncertain',payload:{text:'uncertain input'},turnId:'t2',createdAt:2}];
 const mediaReads=[],openedFiles=[];
 const imageData='data:image/png;base64,'+readFileSync(join(desktop,'assets/logo-source.png')).toString('base64');
 const changes=[{id:'c',path:'/tmp/smoke/example.txt',before:'old\nkeep\n',after:'new\nkeep\n',state:'applied',conflict:false,turnId:'t1',createdAt:1},{id:'conflict',path:'/tmp/smoke/other.txt',before:'x',after:'y',state:'applied',conflict:true,turnId:'t2',createdAt:2}];
 const groups={groups:[{id:'g_saved',name:'原有分组'}],assignments:{s:'g_saved',scheduled:'__scheduled__',c_channel:'g_saved'},collapsed:{},seenAt:{}};
 const newSessions=[],archivedIds=new Set(),startedWorkspaces=[],archiveCalls=[],revealedWorkspaces=[];
 const extraSessions=[{id:'other',title:'Other workspace',workdir:'/other/smoke'},{id:'other-child',title:'Other child',workdir:'/other/smoke',parentId:'other'},{id:'general',title:'General chat',workdir:''},{id:'c_channel',title:'Channel chat',workdir:'/tmp/smoke'},{id:'scheduled',title:'Scheduled chat',workdir:'/tmp/smoke'},{id:'child',title:'Child agent',workdir:'/tmp/smoke',parentId:'s'}].map(s=>({...s,model:'test',turnCount:1,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'}));
 const list=()=>[{id:'s',title:sessionTitle,model:'test',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),turnCount:1,workdir:sessionWorkspace},...(forked?[{id:'fork',title:'Workflow test (fork)',model:'test',turnCount:1,workdir:'/tmp/smoke',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}]:[]),...extraSessions,...newSessions].filter(s=>!archivedIds.has(s.id));
 const handle=(key,fn)=>ipcMain.handle(IPC[key],fn);
 handle('fileMedia',(_e,path)=>{mediaReads.push(path);if(path==='generated/missing.png')throw Error('Image file missing');return {kind:'image',dataUrl:imageData};});
 handle('fileOpen',(_e,path)=>{openedFiles.push(path);return {ok:true,action:'open',detail:''};});
 handle('configRead',()=>config);handle('configWrite',(_e,p)=>Object.assign(config,p));handle('runtimeStart',()=>undefined);
 handle('appVersion',()=> 'work-smoke');handle('profileList',()=>[{id:'on-write',label:'默认'}]);
 handle('groupRead',()=>groups);handle('groupCollapse',(_e,input)=>{groups.collapsed[input.groupId]=input.collapsed;groups.seenAt[input.groupId]=Date.now();return groups;});handle('sessionSearch',()=>list().filter(s=>!s.parentId));handle('mcpRead',()=>mcpServers);handle('skillList',()=>[]);
 handle('providerList',()=>[{id:1,name:'fixture',type:'openai-compatible',enabled:true,apiKeySet:true,models:['test']}]);
 handle('sessionRename',(_e,input)=>{renameCalls.push(input);if(renameFails)throw Error('rename failure');sessionTitle=input.title;return {sessionId:input.sessionId,title:sessionTitle};});
 handle('sessionWorkspace',(_e,input)=>{sessionWorkspace=input.workspace;return sessionWorkspace;});handle('pickDirectory',()=>'/tmp/smoke');handle('workspaceReveal',(_e,path)=>{revealedWorkspaces.push(path);});handle('sessionStart',(_e,input)=>{startedWorkspaces.push(input.workspace);const session={id:'new-workspace',title:'Workspace new chat',workdir:input.workspace,model:'test',turnCount:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};newSessions.push(session);return {sessionId:session.id,workspace:input.workspace,tools:[],mcpStatus:{},model:'test',providerId:1};});handle('sessionArchive',(_e,input)=>{archiveCalls.push(input.sessionId);const ids=[input.sessionId,...list().filter(s=>s.parentId===input.sessionId).map(s=>s.id)];ids.forEach(id=>archivedIds.add(id));return ids;});handle('sessionList',list);handle('sessionArchived',()=>[]);
 handle('approvalPending',()=>[]);handle('questionPending',()=>[]);handle('scheduleList',()=>tasks);
 handle('browserBridgeStatus',()=>({listening:false,port:17891,browser:'',browsers:[]}));
 handle('mcpWrite',(_e,input)=>{mcpServers=input;return input;});handle('mcpProbe',()=>({ok:true,tools:[]}));
 handle('mcpOAuthStatus',()=>({state:authState}));handle('mcpOAuthLogin',(_e,input)=>{authCalls.push(input);authState='authorizing';return {state:authState};});handle('mcpOAuthLogout',()=>{authState='needs_login';return {disconnected:true};});
 handle('sessionConfigure',()=>({tools:[],mcpStatus:{}}));
 handle('scheduleSave',(_e,input)=>{scheduleInputs.push(input);const task={...input,id:'scheduled',enabled:true,lastResult:'waiting for checks',createdAt:new Date().toISOString(),anchorAt:new Date().toISOString()};tasks=[task];return task;});
 handle('sessionResume',(_e,id)=>({sessionId:id,workspace:sessionWorkspace,tools:[],mcpStatus:{},model:'test',providerId:1,history:[{id:'u1',kind:'userMessage',text:'original prompt',at:Date.now()},{id:'tool1',kind:'toolCall',toolName:'generate_image',toolResult:'saved',artifacts:['generated/cat.png','generated/cat.png','generated/dog.webp','generated/missing.png','generated/speech.wav','generated/2026 AI 行业趋势.md','generated/2026 AI 行业趋势.docx','generated/2026 AI 行业趋势.pptx','generated/2026 AI 行业趋势.md']},{id:'search1',kind:'toolCall',toolName:'search__web_search',toolResult:'results',sources:id==='s'?[{title:'AIClaw 文档',url:'https://example.com/docs#one',snippet:'联网搜索返回的功能说明。'},{title:'重复文档',url:'https://example.com/docs#two',snippet:'Duplicate'},{title:'版本更新 <b>说明</b>',url:'https://news.example.com/releases',snippet:'本轮找到的最新发布信息。'},{title:'Unsafe',url:'javascript:alert(1)',snippet:'unsafe'}]:[]},{id:'a1',kind:'agentMessage',text:'original answer\n\n文件路径：`/tmp/smoke/generated/2026 AI 行业趋势.md`（约 7.2 KB）\n\nWord：[打开文档](generated/2026%20AI%20行业趋势.docx)\n\n文档结构：\n- 行业排名\n- 四个关键结论',at:Date.now()}]}));
 handle('sessionWork',(_e,id)=>({goal:id==='s'?goal:null,pending:id==='s'?pending:[],forkSourceId:id==='fork'?'s':'',forkItemId:id==='fork'?'u1':''}));
 handle('changesList',(_e,id)=>id==='s'?changes:[]);
 handle('goalSet',(_e,id,input)=>{goal={...input,status:'active',tokensUsed:0,elapsedMs:0,evidence:'',revision:1};return goal;});
 handle('goalUpdate',(_e,id,update)=>{Object.assign(goal,update);return goal;});
 handle('sessionSend',(_e,input)=>{sends.push(input);setTimeout(()=>{win.webContents.send(IPC.onAgentEvent,{method:'turn/started',params:{sessionId:input.sessionId,turnId:'t'}});setTimeout(()=>win.webContents.send(IPC.onAgentEvent,{method:'turn/completed',params:{sessionId:input.sessionId,turnId:'t'}}),30);},0);return {turnId:'t'};});
 handle('sessionRecover',(_e,id,requestId,action)=>{recoveries.push({requestId,action});pending=pending.filter(p=>p.requestId!==requestId);return {};});
 handle('sessionFork',(_e,id,itemId)=>{forked=true;forks.push({id,itemId});return {sessionId:'fork'};});
 handle('changesUndo',(_e,id,changeId)=>{const change=changes.find(c=>c.id===changeId);if(change.conflict)throw Error('conflict');change.state='undone';return {};});
 win=new BrowserWindow({show:false,width:1200,height:900,webPreferences:{preload:join(desktop,'dist/preload/index.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
 const js=code=>win.webContents.executeJavaScript(code);
 const wait=async code=>{for(let i=0;i<60;i++){if(await js(code))return true;await new Promise(r=>setTimeout(r,50));}return false;};
 const click=async text=>{
  const find=`[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(text)})`;
  if(!(await wait(`(()=>{const b=${find};return !!b&&!b.disabled&&b.getClientRects().length>0})()`)))throw Error('button unavailable: '+text);
  await js(`(${find}).click()`);
 };

 try {
 await win.loadFile(join(desktop,'dist/renderer/index.html'));
 await js("localStorage.setItem('aiclaw:session-grouping','groups');localStorage.removeItem('aiclaw:pinned-workspaces')");
 await win.loadFile(join(desktop,'dist/renderer/index.html'));
 await wait("document.querySelectorAll('.bucket').length===3");
 check('sidebar uses only workspaces and general chats even with an old grouping preference',await js("!document.querySelector('.grouping') && !document.querySelector('.head button[title=\"新建分组\"]') && !document.querySelector('.item-actions button[title=\"移动到分组\"]') && [...document.querySelectorAll('.bucket-name')].map(b=>b.textContent.trim()).join('|')==='smoke|smoke|普通会话' && document.querySelectorAll('.bucket-detail').length===2"));
 check('channel and scheduled chats join their workspace with source labels and child agents stay nested',await js("document.querySelector('[data-bucket-id=\"workspace:/tmp/smoke\"] .count').textContent==='3' && [...document.querySelectorAll('.source-label')].map(b=>b.textContent).sort().join('|')==='定时任务|渠道会话' && !!document.querySelector('.agents-toggle')"));
 check('old custom group data is preserved',groups.groups[0].name==='原有分组' && groups.assignments.s==='g_saved' && groups.assignments.c_channel==='g_saved');
 await js("document.querySelector('[data-bucket-id=\"workspace:/tmp/smoke\"] .fold').click()");
 check('workspace collapse persists by full path',await wait("!document.querySelector('[data-bucket-id=\"workspace:/tmp/smoke\"] .item')")&&groups.collapsed['workspace:/tmp/smoke']===true);
 await win.loadFile(join(desktop,'dist/renderer/index.html'));
 check('workspace stays collapsed after reload',await wait("document.querySelector('[data-bucket-id=\"workspace:/tmp/smoke\"] .fold')?.getAttribute('aria-expanded')==='false'"));
 await js("document.querySelector('[data-bucket-id=\"workspace:/tmp/smoke\"] .fold').click()");
 await js("(()=>{const input=document.querySelector('.search input');input.value='chat';input.dispatchEvent(new Event('input',{bubbles:true}));})()");
 check('global search labels workspaces and includes general and channel chats',await wait("document.querySelectorAll('.workspace-label').length===5")&&await js("[...document.querySelectorAll('.workspace-label')].some(b=>b.textContent.includes('/other/')) && document.querySelector('.sidebar .list').textContent.includes('Channel chat')"));
 await js("(()=>{const input=document.querySelector('.search input');input.value='';input.dispatchEvent(new Event('input',{bubbles:true}));})()");
 await wait("document.querySelectorAll('.bucket').length===3 && !!document.querySelector('.composer .chip')");
 await js("[...document.querySelectorAll('.composer .chip')].find(b=>b.textContent.includes('smoke')).click()");
 await click('清除（回到未设置）');
 check('clearing workspace immediately moves the chat to general chats',await wait("document.querySelector('[data-bucket-id=\"workspace:/tmp/smoke\"] .count').textContent==='2' && document.querySelector('[data-bucket-id=\"__ungrouped__\"] .count').textContent==='2'"));
 await js("[...document.querySelectorAll('.composer .chip')].find(b=>b.textContent.includes('未设工作区')).click()");
 await click('选择目录…');
 check('choosing workspace immediately restores the matching workspace bucket',await wait("document.querySelector('[data-bucket-id=\"workspace:/tmp/smoke\"] .count')?.textContent==='3'"));
 await js("new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");
 writeFileSync('/tmp/aiclaw-workspace-sidebar.png',(await win.webContents.capturePage()).toPNG());
 mediaReads.length=0;
 await win.loadFile(join(desktop,'dist/renderer/index.html'));

 check('work panel rendered',await wait("!!document.querySelector('.work-panel') && [...document.querySelectorAll('.work-panel article')].some(a=>a.textContent.includes('uncertain input'))"));
 check('uncertain input has no replay action',await js("[...document.querySelectorAll('.work-panel article')].find(a=>a.textContent.includes('uncertain input')).querySelectorAll('button').length===1"));
 await click('处理这条输入');await wait("!document.querySelector('.work-panel').textContent.includes('queued input')");
 await click('已检查，移除恢复提示');await wait("!document.querySelector('.work-panel').textContent.includes('uncertain input')");
 check('generated image visible outside collapsed steps after history restore',await wait("document.querySelector('.generated-images img')?.naturalWidth>0 && !document.querySelector('.steps-body')"));
 check('history search sources render one deduplicated entry per safe URL',await wait("document.querySelector('.sources-trigger')?.textContent.includes('参考来源 · 2')"));
 await js("document.querySelector('.sources-trigger').click()");
 check('sources drawer shows domains titles and snippets as plain text with focus',await wait("document.querySelectorAll('.source-card').length===2")&&await js("document.querySelector('.sources-drawer').contains(document.activeElement) && [...document.querySelectorAll('.source-title')].some(b=>b.textContent==='版本更新 <b>说明</b>') && !document.querySelector('.source-title b') && document.querySelector('.source-domain').textContent.includes('example.com') && document.querySelector('.source-snippet').textContent.includes('功能说明')"));
 const sourceLinks=[];win.webContents.setWindowOpenHandler(({url})=>{sourceLinks.push(url);return {action:'deny'};});
 await js("document.querySelector('.source-card').click()");
 check('source card opens its exact HTTP URL',await wait("!!document.querySelector('.sources-drawer')")&&sourceLinks[0]==='https://example.com/docs');
 writeFileSync('/tmp/aiclaw-search-sources.png',(await win.webContents.capturePage()).toPNG());
 await js("document.querySelector('.source-card:last-child').focus();document.querySelector('.sources-drawer').dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true}))");
 check('source dialog traps keyboard focus',await js("document.activeElement.classList.contains('sources-close')"));
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});
 check('Escape closes sources and restores trigger focus',await wait("!document.querySelector('.sources-drawer')")&&await js("document.activeElement.classList.contains('sources-trigger')"));
 await js("document.querySelector('.sources-trigger').click()");
 await wait("!!document.querySelector('.sources-overlay')");
 await js("document.querySelector('.sources-overlay').click()");
 check('click outside closes source panel',await wait("!document.querySelector('.sources-drawer')"));
 check('user timestamp leads compact labelled icon buttons',await js("document.querySelector('.user-meta')?.firstElementChild.tagName==='TIME' && document.querySelectorAll('.user-meta button').length===2 && [...document.querySelectorAll('.user-meta button')].every(b=>b.getAttribute('aria-label')&&b.querySelector('svg')&&!b.querySelector('span'))"));
 check('user toolbar aligns with bubble right edge',await js("Math.abs(document.querySelector('.bubble').getBoundingClientRect().right-document.querySelector('.user-meta button:last-child').getBoundingClientRect().right)<1"));
 check('answer timestamp leads the icon toolbar',await js("document.querySelector('.agent-meta')?.firstElementChild.tagName==='TIME'"));
 check('answer actions use labelled icon buttons',await js("document.querySelectorAll('.agent-meta button').length===4 && [...document.querySelectorAll('.agent-meta button')].every(b=>b.getAttribute('aria-label')&&b.querySelector('svg')) && !document.querySelector('.agent-meta .meta-fork span')"));
 await js("document.querySelectorAll('.agent-meta .meta-feedback').forEach(b=>{if(b.getAttribute('aria-pressed')==='true')b.click()})");
 await js("document.querySelector('.agent-meta button[aria-label=\"有帮助\"]').click()");
 check('helpful feedback selects',await wait("document.querySelector('.agent-meta button[aria-label=\"有帮助\"]')?.getAttribute('aria-pressed')==='true'"));
 await js("document.querySelector('.agent-meta button[aria-label=\"没帮助\"]').click()");
 check('feedback choices are mutually exclusive',await wait("document.querySelector('.agent-meta button[aria-label=\"没帮助\"]')?.getAttribute('aria-pressed')==='true' && document.querySelector('.agent-meta button[aria-label=\"有帮助\"]')?.getAttribute('aria-pressed')==='false'"));
 mediaReads.length=0;
 await win.loadFile(join(desktop,'dist/renderer/index.html'));
 check('feedback survives conversation reload',await wait("document.querySelector('.agent-meta button[aria-label=\"没帮助\"]')?.getAttribute('aria-pressed')==='true'"));
 await js("document.querySelector('.agent-meta button[aria-label=\"没帮助\"]').click()");
 check('clicking selected feedback cancels it',await wait("[...document.querySelectorAll('.agent-meta .meta-feedback')].every(b=>b.getAttribute('aria-pressed')==='false')"));
 await js("new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");
 writeFileSync('/tmp/aiclaw-answer-actions.png',(await win.webContents.capturePage()).toPNG());
 check('only unmentioned files remain below the answer without summary heading',await js("!document.querySelector('.generated-files h3') && document.querySelectorAll('.generated-files .file-card').length===2 && document.querySelectorAll('.prose .file-card').length===2"));
 check('document cards show filenames and types without reading file contents',await js("[...document.querySelectorAll('.file-card')].some(b=>b.textContent.includes('DOCX')&&b.textContent.includes('2026 AI 行业趋势.docx'))")&&!mediaReads.some(p=>p.endsWith('.docx')));
 await js("[...document.querySelectorAll('.file-card')].find(b=>b.textContent.includes('2026 AI 行业趋势.docx')).click()");
 check('document card opens exact path through preload',openedFiles.pop()==='generated/2026 AI 行业趋势.docx');
 check('inline file cards hide directories while retaining exact paths',await js("document.querySelector('.prose .file-card').getAttribute('data-file-path')==='/tmp/smoke/generated/2026 AI 行业趋势.md' && !document.querySelector('.prose').textContent.includes('/tmp/smoke/')"));
 await js("document.querySelector('.prose .file-card').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}))");
 check('inline file card opens by keyboard using full path',openedFiles.pop()==='/tmp/smoke/generated/2026 AI 行业趋势.md');
 check('chat uses flat reference background',await js("getComputedStyle(document.querySelector('.chat')).backgroundColor==='rgb(243, 248, 244)' && getComputedStyle(document.body).backgroundImage==='none'"));

 writeFileSync('/tmp/aiclaw-inline-files.png',(await win.webContents.capturePage()).toPNG());
 check('image artifacts deduplicated and audio excluded',mediaReads.filter(p=>p==='generated/cat.png').length===1&&!mediaReads.includes('generated/speech.wav'));
 check('missing image reports local error without hiding answer',await wait("document.querySelector('.generated-images .image-error')?.textContent.includes('Image file missing') && document.querySelector('.prose')?.textContent.includes('original answer')"));
 await js("document.querySelector('.generated-images .image-preview').click()");
 check('image click opens full size dialog',await wait("document.querySelector('.image-viewer[open] img')?.naturalWidth>0"));
 writeFileSync('/tmp/aiclaw-generated-image-viewer.png',(await win.webContents.capturePage()).toPNG());
 await js("document.querySelector('.viewer-close').click()");
 check('image dialog closes',await wait("!document.querySelector('.image-viewer[open]')"));
 await js("document.querySelector('.generated-images .image-preview').click()");
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});
 win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});
 check('Escape closes image dialog',await wait("!document.querySelector('.image-viewer[open]')"));
 await js("document.querySelector('.generated-images .image-path').click()");
 check('image filename opens generated file',openedFiles[0]==='generated/cat.png');
 check('multiple images form a thumbnail row',await js("document.querySelector('.generated-images.multiple').querySelectorAll('.image-preview').length===2"));
 writeFileSync('/tmp/aiclaw-generated-images.png',(await win.webContents.capturePage()).toPNG());
 win.webContents.send(IPC.onAgentEvent,{method:'turn/started',params:{sessionId:'s',turnId:'image-turn'}});
 win.webContents.send(IPC.onAgentEvent,{method:'item/completed',params:{sessionId:'s',item:{id:'image-user',kind:'userMessage',text:'draw another cat'}}});
 win.webContents.send(IPC.onAgentEvent,{method:'item/completed',params:{sessionId:'s',item:{id:'image-live',kind:'toolCall',toolName:'generate_image',toolResult:'saved',artifacts:['generated/live.png','generated/live.md']}}});
 check('unfinished answer does not offer feedback',await wait("document.querySelectorAll('.agent-meta').length===1"));
 check('live output summary appears before answer and stays scoped to its turn',await wait("document.querySelectorAll('.generated-files').length===2 && document.querySelectorAll('.generated-files')[1].querySelectorAll('.file-card').length===1"));
 check('single generated image previews before assistant prose arrives',await wait("[...document.querySelectorAll('.generated-images:not(.multiple) img')].some(img=>img.alt==='generated/live.png'&&img.naturalWidth>0)"));
 check('single image is larger than thumbnails and scrolled into view',await wait("(()=>{const img=document.querySelector('.generated-images:not(.multiple) img');const stream=document.querySelector('.stream');return img?.getBoundingClientRect().width>document.querySelector('.generated-images.multiple img').getBoundingClientRect().width && img.getBoundingClientRect().bottom<=stream.getBoundingClientRect().bottom;})()"));
 writeFileSync('/tmp/aiclaw-generated-single-image.png',(await win.webContents.capturePage()).toPNG());
 win.webContents.send(IPC.onAgentEvent,{method:'turn/completed',params:{sessionId:'s',turnId:'image-turn'}});
 check('recovery actions use request identities',recoveries.length===2&&recoveries[0].action==='resume'&&recoveries[1].action==='dismiss');

 const openRename=async()=>{await js("document.querySelector('.sidebar button[aria-label=\"重命名会话\"]').click()");await wait("!!document.querySelector('.session-rename input')");};
 const nameDraft=async text=>{await js(`(()=>{const input=document.querySelector('.session-rename input');input.value=${JSON.stringify(text)};input.dispatchEvent(new Event('input',{bubbles:true}));})()`);};
 await openRename();await nameDraft('   ');
 check('blank chat names cannot be submitted',await js("document.querySelector('.session-rename button[type=submit]').disabled"));
 await nameDraft('  新会话名称 🐾  ');await js("document.querySelector('.session-rename').requestSubmit()");
 check('rename crosses preload and updates sidebar',await wait("!document.querySelector('.session-rename') && document.querySelector('.sidebar').textContent.includes('新会话名称 🐾')")&&renameCalls[0]?.sessionId==='s'&&renameCalls[0]?.title==='新会话名称 🐾');
 await openRename();await nameDraft('discard this');await js("document.querySelector('.session-rename input').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");
 check('Escape cancels without changing the chat name',await wait("!document.querySelector('.session-rename')")&&renameCalls.length===1&&sessionTitle==='新会话名称 🐾');
 await openRename();await nameDraft('Retry name');renameFails=true;await js("document.querySelector('.session-rename').requestSubmit()");
 check('rename failure preserves editable draft',await wait("document.querySelector('.session-rename [role=alert]')?.textContent.includes('rename failure')")&&await js("document.querySelector('.session-rename input').value==='Retry name'"));
 renameFails=false;await js("document.querySelector('.session-rename').requestSubmit()");await wait("!document.querySelector('.session-rename')");
 check('rename retry succeeds and survives sidebar reload',sessionTitle==='Retry name'&&renameCalls.length===3);
 await click('设置目标');await wait("!!document.querySelector('.goal-form')");
 await js("(()=>{const fields=document.querySelectorAll('.goal-form textarea');['Ship work','Tests pass','Implement\\nVerify'].forEach((v,i)=>{fields[i].value=v;fields[i].dispatchEvent(new Event('input',{bubbles:true}));});})()");
 await click('创建并开始');await wait("document.querySelector('.work-panel').textContent.includes('Ship work') && !document.querySelector('.goal-form')");
 check('goal creation passes criteria and plan through preload',goal?.acceptance==='Tests pass'&&goal.steps.length===2&&sends.length===1);
 await click('暂停目标');await wait("document.querySelector('.work-panel').textContent.includes('已暂停')");
 check('goal pause rendered',goal.status==='paused');
 await click('继续目标');await wait("document.querySelector('.work-panel').textContent.includes('进行中')");
 check('goal resumes and dispatches continuation',goal.status==='active'&&sends.length===2);
 await click('暂停目标');await wait("document.querySelector('.work-panel').textContent.includes('已暂停')");
 await js("[...document.querySelectorAll('.work-panel summary')].find(s=>s.textContent.includes('调整预算')).click()");
 await new Promise(r=>setTimeout(r,60));
 await js("(()=>{const inputs=document.querySelectorAll('.work-panel input[type=number]');[200,2].forEach((v,i)=>{inputs[i].value=String(v);inputs[i].dispatchEvent(new Event('input',{bubbles:true}));});})()");
 await click('保存预算');await wait("document.querySelector('.work-panel').textContent.includes('200')");
 check('budget edit crosses the IPC bridge',goal.tokenBudget===200&&goal.timeBudgetMs===120000);
 for(let index=0;index<2;index++){
  await js(`(()=>{const input=document.querySelectorAll('.work-panel select')[${index}];input.value='completed';input.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await wait("![...document.querySelectorAll('.work-panel button')].find(b=>b.textContent.trim()==='保存预算').disabled");
 }
 await js("(()=>{const input=document.querySelector('.work-panel textarea');input.value='Tests verified';input.dispatchEvent(new Event('input',{bubbles:true}));})()");
 await click('标记完成');await wait("!document.querySelector('.work-panel textarea')");
 check('completion records evidence and finished steps',goal.status==='complete'&&goal.evidence==='Tests verified'&&goal.steps.every(s=>s.status==='completed'));
 goal={...goal,tokensUsed:123};win.webContents.send(IPC.onAgentEvent,{method:'session/workUpdated',params:{sessionId:'s',goal}});
 check('goal updates stream independently of tool display mode',await wait("document.querySelector('.work-panel').textContent.includes('123')"));

 await js("[...document.querySelectorAll('.work-panel summary')].find(s=>s.textContent.includes('文件改动')).click()");
 await click('/tmp/smoke/example.txt');check('file diff renders additions and deletions',await wait("document.querySelector('.diff .add')?.offsetHeight>0 && document.querySelector('.diff .remove')?.offsetHeight>0"));
 check('conflicting edit offers no undo',await js("[...document.querySelectorAll('.work-panel article')].find(a=>a.textContent.includes('other.txt')).querySelectorAll('button').length===1"));
 writeFileSync('/tmp/aiclaw-work-panel.png',(await win.webContents.capturePage()).toPNG());
 await click('撤销此改动');await wait("document.querySelector('.work-panel').textContent.includes('已撤销')");check('undo uses selected change',changes[0].state==='undone');
 await js("document.querySelector('.user-meta .meta-fork').click()");await wait("document.querySelector('.work-panel').textContent.includes('查看来源会话')");
 check('fork uses chosen message and opens provenance',forks.length===1&&forks[0].itemId==='u1'&&await js("document.querySelector('.work-panel').textContent.includes('查看来源会话')"));
 check('ordinary chat does not display another chats sources',await wait("!document.querySelector('.sources-trigger') && !document.querySelector('.sources-drawer')"));
 win.webContents.send(IPC.onAgentEvent,{method:'item/completed',params:{sessionId:'fork',item:{id:'live-search',kind:'toolCall',toolName:'search__web_search',sources:[{title:'Live result',url:'https://live.example.com/',snippet:'Live summary'}]}}});
 check('live tool completion displays sources without reloading history',await wait("document.querySelector('.sources-trigger')?.textContent.includes('参考来源 · 1')"));


 await click('⚙');
 const nav = async title => { const selector=`[...document.querySelectorAll('.sidebar .item')].find(item=>item.querySelector('.title')?.textContent.trim()===${JSON.stringify(title)})`;await wait(`!!(${selector})`);await js(`(${selector}).click()`); };
 await nav('MCP');await wait("!!document.querySelector('.card .disclose')");await js("document.querySelector('.card .disclose').click()");
 check('OAuth settings render status and credentials form',await wait("document.querySelector('.oauth')?.textContent.includes('需要登录')"));
 await js("(()=>{const input=document.querySelector('.oauth input[type=password]');input.value='client-secret';input.dispatchEvent(new Event('input',{bubbles:true}));})()");
 await click('登录');await wait("document.querySelector('.oauth').textContent.includes('等待浏览器授权')");
 check('OAuth login crosses preload without saving secret in config',authCalls[0]?.clientSecret==='client-secret'&&!JSON.stringify(mcpServers).includes('client-secret'));
 authState='connected';check('OAuth callback status becomes visible',await wait("document.querySelector('.oauth').textContent.includes('已登录')"));
 await click('退出登录');check('OAuth logout updates status',await wait("document.querySelector('.oauth').textContent.includes('需要登录')"));
 await nav('定时任务');await click('+ 新建定时任务');await wait("!!document.querySelector('.editor')");
 await js("(()=>{const root=document.querySelector('.editor');const field=label=>[...root.querySelectorAll('label')].find(l=>l.querySelector('span')?.textContent.trim()===label);const set=(label,value)=>{const input=field(label).querySelector('input,textarea,select');input.value=value;input.dispatchEvent(new Event(input.tagName==='SELECT'?'change':'input',{bubbles:true}));};set('名称','Follow up');set('要做什么','Check progress');set('停止条件（可选）','All checks pass');})()");
 await click('建好');await wait("!document.querySelector('.editor')");
 check('follow-up form sends chat, notification and stop condition',scheduleInputs[0]?.mode==='followup'&&scheduleInputs[0]?.sessionId==='fork'&&scheduleInputs[0]?.notificationPolicy==='changes'&&scheduleInputs[0]?.stopWhen==='All checks pass');
 await nav('MCP');await nav('定时任务');check('last follow-up result renders after reload',await wait("document.querySelector('.page').textContent.includes('waiting for checks')"));
 await js("document.querySelector('.sidebar .head .new').click()");
 await wait("!!document.querySelector('[data-bucket-id=\"workspace:/other/smoke\"]')");
 const workspaceMore=async()=>{await js("document.querySelector('[data-bucket-id=\"workspace:/other/smoke\"] button[aria-label=\"工作区更多操作\"]').click()");await wait("!!document.querySelector('.workspace-menu')");};
 await workspaceMore();
 check('workspace menu supports pin reveal and archive with keyboard focus',await js("document.querySelector('.workspace-menu').textContent.includes('置顶') && document.querySelector('.workspace-menu').textContent.includes('在 Finder 中显示') && document.querySelector('.workspace-menu').textContent.includes('归档工作区会话') && document.querySelector('.workspace-menu').contains(document.activeElement)"));
 await js("new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");
 writeFileSync('/tmp/aiclaw-workspace-menu.png',(await win.webContents.capturePage()).toPNG());
 await click('置顶');
 check('pin reorders exact workspace without merging same-name directories',await wait("document.querySelector('.bucket').getAttribute('data-bucket-id')==='workspace:/other/smoke'")&&await js("document.querySelectorAll('.bucket-detail').length===2"));
 await win.loadFile(join(desktop,'dist/renderer/index.html'));
 check('workspace pin survives reload',await wait("document.querySelector('.bucket')?.getAttribute('data-bucket-id')==='workspace:/other/smoke' && !!document.querySelector('.workspace-pin')"));
 await workspaceMore();await click('在 Finder 中显示');
 check('workspace reveal passes full directory path through preload',revealedWorkspaces[0]==='/other/smoke');
 await workspaceMore();
 await js("document.querySelector('.workspace-menu').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}))");
 check('Escape closes workspace menu and returns focus to trigger',await wait("!document.querySelector('.workspace-menu')")&&await js("document.activeElement.getAttribute('aria-label')==='工作区更多操作'"));
 await workspaceMore();await click('取消置顶');
 check('unpin restores recent-workspace ordering',await wait("document.querySelector('.bucket').getAttribute('data-bucket-id')==='workspace:/tmp/smoke'"));
 await wait("!document.querySelector('[data-bucket-id=\"workspace:/other/smoke\"] button[aria-label=\"在此工作区新建会话\"]').disabled");
 await js("document.querySelector('[data-bucket-id=\"workspace:/other/smoke\"] button[aria-label=\"在此工作区新建会话\"]').click()");
 check('workspace new chat inherits its full path',await wait("document.querySelector('[data-bucket-id=\"workspace:/other/smoke\"] .count').textContent==='2'")&&startedWorkspaces[0]==='/other/smoke');
 await workspaceMore();await js("window.confirm=()=>false;true");await click('归档工作区会话');
 check('cancelling workspace archive changes no chats',archiveCalls.length===0);
 await workspaceMore();
 await js("window.confirm=message=>{window.archiveConfirmation=message;return true};true");
 await click('归档工作区会话');
 check('workspace archive includes children and leaves other workspaces untouched',await wait("!document.querySelector('[data-bucket-id=\"workspace:/other/smoke\"]')")&&archiveCalls.length===2&&archivedIds.has('other-child')&&!archivedIds.has('s')&&!archivedIds.has('child')&&await js("window.archiveConfirmation.includes('3 个会话')"));
 }catch(e){check(String(e.stack||e),false);}
 console.log(`${checks.filter(c=>c.ok).length}/${checks.length} work UI checks passed`);
 app.exit(checks.every(c=>c.ok)?0:1);
});
